version: '3.9'
services:
  database:
    image: postgres
    container_name: database_fiveDevs
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=fiveDevs
      - POSTGRES_PASSWORD=fiveDevs123
      - POSTGRES_DB=fiveDevs
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: fiveDevs
    ports:
      - 3000:3000
    volumes:
      - .:/user/app
    network_mode: host
volumes:
  pgdata:
    driver: local